#Weather app
JulianaOsemeke/weather-app pull request #1
Opened 2021-07-27 21:59 UTC by JulianaOsemeke

# weather-app
A simple weather app that extracts information from the openweathermap.org/api thereby enabling users accurately forecast weather conditions in different cities. This app was built with Javascript and Webpack with emphasis on the async/await concept.

2021-08-14 12:15 UTC, rukundoeric commented
Hi @JulianaOsemeke, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] You did put `node_modules/` in `.gitignore` but still, node_modules files are committed and pushed to your remote repo. This is because you might have added the `node_modules` to `.gitignore` after committing the files. to fix this kindly run this command. `git rm --cached -r node_modules`. (learn more [here](https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste))
  - [ ] You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.
  
  - [ ]  The app should have  a toggle control to determine if the result will be shown in Celsius or Fahrenheit (There are two valid solutions: students can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
  - [ ] Kindly try to separate logic from DOM Manipulation. this will help you to increase the readability of your code.
  - [ ] When trying to search a city's weather, here is the error I got. kindly fix it.
  ![Screen Shot 2021-08-14 at 13 40 07](https://user-images.githubusercontent.com/45217364/129445894-08258018-2f3c-4ee3-b0de-739cd0435812.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-08-14 12:17 UTC, rukundoeric requested changes
Hi @JulianaOsemeke, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] You did put `node_modules/` in `.gitignore` but still, node_modules files are committed and pushed to your remote repo. This is because you might have added the `node_modules` to `.gitignore` after committing the files. to fix this kindly run this command. `git rm --cached -r node_modules`. (learn more [here](https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste))
  - [ ] You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.
  
  - [ ]  The app should have  a toggle control to determine if the result will be shown in Celsius or Fahrenheit (There are two valid solutions: students can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
  - [ ] Kindly try to separate logic from DOM Manipulation. this will help you to increase the readability of your code.
  - [ ] When trying to search a city's weather, here is the error I got. kindly fix it.
  ![Screen Shot 2021-08-14 at 13 40 07](https://user-images.githubusercontent.com/45217364/129445894-08258018-2f3c-4ee3-b0de-739cd0435812.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-08-16 09:40 UTC, JulianaOsemeke commented
Hello. I have made the requested changes, however I have been unable to  remove the node modules with the command provided after several attempts. Thank you

2021-08-16 10:01 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes. 
### Changes
- remove the node_modules folder. Learn how [here](https://github.community/t/how-to-delete-multiples-files-in-github/702)
- add a toggle button to change the temperature unit
- remove the dom-related logic in src/index on lines 15 and 16. Move that to dom.js

### Martin Afani
#### Slack: whiz25

2021-08-20 06:27 UTC, JulianaOsemeke commented
Hello, I have made the following requested changes
-Removed the node modules as instructed
-Included a button that toggles between Celsius and Fahrenheit temperature units when clicked
-Removed the dom-related logic in src/index on lines 15 and 16

2021-08-20 06:56 UTC, bellom approved these changes
## Hi @JulianaOsemeke  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best**

2021-08-20 06:56 UTC, bellom commented on dist/index.html
> +              <p>30&deg;C</p>
### [Optional]
Kindly remove this hardcoded Celcius that might confuse users from the actual data.

2021-08-20 07:26 UTC, merged